### ISSUE TITLE
Chat App Errors Out

### ISSUE THREAD

**Issue by LawJolla** [shanecav/horizon-redux#1] opened 2016-08-11 20:36 UTC
Hi Shane,

I followed your instructions and found the following errors on npm start.

`ERROR in ./app/horizon/redux.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../../lib in /Users/wheelkinetics/Repos/horizon-redux/examples/chat-app/app/horizon
 @ ./app/horizon/redux.js 16:17-43`

I tried setting USE_LIB to false, but that didn't seem to work.  I changed chat-app/app/horizon/redux to
`
import horizon from './connection'

const HorizonRedux = require('../../../../src').default

const horizonRedux = HorizonRedux(horizon)

export default horizonRedux
`

Then on npm start..

`ERROR in /Users/wheelkinetics/Repos/horizon-redux/src/index.js
Module build failed: ReferenceError: Unknown plugin "transform-flow-strip-types" specified in "/Users/wheelkinetics/Repos/horizon-redux/.babelrc" at 0, attempted to resolve relative to "/Users/wheelkinetics/Repos/horizon-redux"`

I ran npm install on horizon-redux.  The plugin loaded, and npm start on chat-app worked without error.

The browser returns a 404:
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (index.js.map, line 0)`

And when I type into the text box and hit return, the action dispatches but nothing is saved to the database or updated to the screen.  Also, no error is returned on the server (in debug mode) or the console.  I opened up the Rethink admin console, and the "chat_app" database is built out.

This is using 2.0 beta 3.

From there I'm stuck.

**Comment by shanecav** [comment] 2016-08-11 21:24
Hey @LawJolla, thanks for reporting this. I just pushed a change that should fix the two errors you were seeing. Can you pull from master and `npm install` in examples/chat-app again and let me know if you're still running into issues?

I haven't tested with the 2.0 beta yet, so I'm not sure if that's related. I'll check that out soon.

**Comment by LawJolla** [comment] 2016-08-11 22:26
Great thanks!

The ../lib error is gone, but the transform-flow-strip-types remains.  

Webpack is traversing up the tree to the top level .babelrc file and then looking in that node_modules.  I don't know Webpack well enough to make it stop -- I tried to add a resolve.moduleDirectories to the config but that didn't work.

When I installed the plugin in the top level node_modules, it loaded without error.

It initializes fine, but quickly throws a "Horizon Disconnected" action.  I'll keep playing with it... probably a 2.0 beta issue.

It is still looking for http://localhost:3000/index.js.map (404)

**Comment by shanecav** [comment] 2016-08-11 22:34
Hmm, that's odd. The chat-app example's package.json definitely includes babel-plugin-transform-flow-strip-types as a dependency now, so I'm not sure why it would be looking in the root node_modules. Did you `npm install` in examples/chat-app after pulling?

I'm guessing the disconnect issue is related to Horizon 2.0. I'll be working on supporting that soon, but for now I'd recommend using horizon-redux with Horizon 1.x until 2.0 is released.

**Comment by shanecav** [comment] 2016-08-11 22:39
I was able to reproduce what you're seeing, working on it now.

**Comment by LawJolla** [comment] 2016-08-11 22:40
I'm pretty good when it comes to my code, terrible when it comes to someone else's code.

**Comment by shanecav** [comment] 2016-08-11 23:18
Alright, I realized that running 'npm install' in the root directory is actually just a required step in getting the example to work, because of the way babel looks at .babelrc files in every directory it's loading modules from (I didn't realize babel worked that way). I updated the instructions in examples/chat-app/README.md to reflect that requirement, so it should be good now.

I'm going to close the issue, but please do let me know if you still have any issues with the example using Horizon 1.x. Thanks again!

**Closed as completed by shanecav** 2016-08-11 23:18 UTC
